name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Microsoft Edge WebDriver
      run: |
        # Download and install Edge WebDriver
        wget https://msedgedriver.azureedge.net/latest/edgedriver_linux64.zip
        unzip edgedriver_linux64.zip
        sudo mv msedgedriver /usr/local/bin/msedgedriver
        sudo chmod +x /usr/local/bin/msedgedriver

    - name: Run Selenium Tests
      run: |
        mvn clean test -Dwebdriver.edge.driver=/usr/local/bin/msedgedriver
